#!/usr/bin/env python3
"""
Skill Auto-Creation Detector for WorkBuddy
============================================
Inspired by Hermes Agent's autonomous skill creation.

Analyzes session patterns and tool usage to detect reusable workflows
that could be codified as Skills.

Usage:
    # Check if skill creation is warranted
    python3 skill_detector.py --workspace <cwd> --check

    # Analyze current session for patterns
    python3 skill_detector.py --workspace <cwd> --analyze

    # Generate a skill template
    python3 skill_detector.py --workspace <cwd> --generate --name "my-skill"

    # List detected patterns
    python3 skill_detector.py --workspace <cwd> --list-patterns
"""

import argparse
import json
import os
import re
import sqlite3
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional


# ── Constants ────────────────────────────────────────────────

from ..constants import (
    WORKBUDDY_DIR, WORKBUDDY_ROOT, SKILLS_DIR, SCRIPTS_DIR, MEMORY_DIR,
    MIN_REPEATED_TOOLS, MIN_SESSION_OCCURRENCES, MIN_COMPLEXITY_SCORE,
    # Phase 3: 复合评分常量
    MIN_COMPLEX_TOOL_CALLS, MIN_FILE_OPERATIONS, MIN_ERROR_RECOVERY,
    MIN_PATTERN_SIMILARITY, COMPOSITE_SCORE_THRESHOLD, AUTO_INSTALL_THRESHOLD,
    WEIGHT_TOOL_CALLS, WEIGHT_FILE_OPERATIONS, WEIGHT_ERROR_RECOVERY,
    WEIGHT_SIMILARITY, NORM_TOOL_CALLS, NORM_FILE_OPERATIONS, NORM_ERROR_RECOVERY,
)

SKILL_TEMPLATE = """---
name: {name}
description: >-
  {description}
agent_created: true
---

# {title}

## When to Use
{trigger_conditions}

## Steps
{steps}

## Configuration
{configuration}

## Notes
- Auto-generated by enhanced-memory Skill Detector on {date}
- Composite score: {composite_score:.3f} (threshold: {threshold:.2f})
- Review and adjust as needed
"""


# ── Phase 3: 复合评分引擎 ──────────────────────────────────

def _normalize(value: float, norm: float) -> float:
    """归一化原始计数到 [0, 1]，超过 norm 时裁剪为 1.0。"""
    return min(value / norm, 1.0) if norm > 0 else 0.0


def count_file_operations(content: str) -> int:
    """统计会话内容中的文件操作次数 (Read/Write/Edit/Glob/Bash with file)。"""
    patterns = [
        r'\bRead\b', r'\bWrite\b', r'\bEdit\b', r'\bGlob\b',
        r'\bBash\b.*?(?:>\s*|>>\s*|tee\s+|cp\s+|mv\s+|rm\s+)',  # Bash 文件写入
    ]
    count = 0
    for pat in patterns:
        count += len(re.findall(pat, content))
    return count


def detect_error_recovery(content: str) -> int:
    """
    检测错误恢复模式: 重试 / fallback / 降级。
    模式包括: 'retry', 'retrying', 'fallback', 'fall back',
    'try again', 'attempt.*again', 'Error.*→', '重新.*尝试',
    '回退', '降级', 'alternative approach'.
    """
    recovery_patterns = [
        r'\bretry(?:ing)?\b', r'\bfall\s*back\b', r'\bfallback\b',
        r'try\s+again', r'attempt.*?(?:again|alternative)',
        r'Error.*?→', r'[Ee]rror.*?(?:retry|switch|alternative)',
        r'重新(?:尝试|执行)', r'回退', r'降级',
        r'alternative\s+(?:approach|method|strategy)',
        r'switch(?:ed|ing)?\s+(?:to|approach)',
    ]
    count = 0
    for pat in recovery_patterns:
        count += len(re.findall(pat, content, re.IGNORECASE))
    return count


def compute_pattern_similarity(patterns: list) -> float:
    """
    计算跨会话工具使用模式的 Jaccard 相似度。
    将每个 pattern 的 actions 转为集合，计算平均两两 Jaccard 系数。
    如果 patterns < 2，返回 0.0。
    """
    if len(patterns) < 2:
        return 0.0

    action_sets = []
    for p in patterns:
        actions = set(p.get("actions", []) or [])
        if actions:
            action_sets.append(actions)

    if len(action_sets) < 2:
        return 0.0

    jaccards = []
    for i in range(len(action_sets)):
        for j in range(i + 1, len(action_sets)):
            a, b = action_sets[i], action_sets[j]
            intersection = len(a & b)
            union = len(a | b)
            if union > 0:
                jaccards.append(intersection / union)

    if not jaccards:
        return 0.0

    return sum(jaccards) / len(jaccards)


def calculate_composite_score(
    tool_call_count: int,
    file_op_count: int,
    error_recovery_count: int,
    pattern_similarity: float,
) -> dict:
    """
    计算复合评分 (Composite Score)。

    四个维度分别归一化到 [0, 1]，加权求和得最终分。

    Returns:
        dict with keys: composite_score, meets_threshold, meets_auto_install,
                        dimensions (各维度原始值 + 归一化值 + 是否达标)
    """
    # 归一化
    norm_tools = _normalize(tool_call_count, NORM_TOOL_CALLS)
    norm_files = _normalize(file_op_count, NORM_FILE_OPERATIONS)
    norm_recovery = _normalize(error_recovery_count, NORM_ERROR_RECOVERY)
    norm_similarity = pattern_similarity  # 已在 [0, 1] 范围

    # 加权求和
    composite = (
        WEIGHT_TOOL_CALLS * norm_tools
        + WEIGHT_FILE_OPERATIONS * norm_files
        + WEIGHT_ERROR_RECOVERY * norm_recovery
        + WEIGHT_SIMILARITY * norm_similarity
    )

    # 硬阈值检查
    hard_thresholds_met = (
        tool_call_count >= MIN_COMPLEX_TOOL_CALLS
        and file_op_count >= MIN_FILE_OPERATIONS
        and error_recovery_count >= MIN_ERROR_RECOVERY
        and pattern_similarity >= MIN_PATTERN_SIMILARITY
    )

    return {
        "composite_score": round(composite, 4),
        "meets_threshold": composite >= COMPOSITE_SCORE_THRESHOLD and hard_thresholds_met,
        "meets_auto_install": composite >= AUTO_INSTALL_THRESHOLD and hard_thresholds_met,
        "hard_thresholds": {
            "tool_calls": {"value": tool_call_count, "threshold": MIN_COMPLEX_TOOL_CALLS, "met": tool_call_count >= MIN_COMPLEX_TOOL_CALLS},
            "file_ops": {"value": file_op_count, "threshold": MIN_FILE_OPERATIONS, "met": file_op_count >= MIN_FILE_OPERATIONS},
            "error_recovery": {"value": error_recovery_count, "threshold": MIN_ERROR_RECOVERY, "met": error_recovery_count >= MIN_ERROR_RECOVERY},
            "similarity": {"value": round(pattern_similarity, 3), "threshold": MIN_PATTERN_SIMILARITY, "met": pattern_similarity >= MIN_PATTERN_SIMILARITY},
        },
        "dimensions": {
            "tool_calls": {"raw": tool_call_count, "normalized": round(norm_tools, 3), "weight": WEIGHT_TOOL_CALLS},
            "file_ops": {"raw": file_op_count, "normalized": round(norm_files, 3), "weight": WEIGHT_FILE_OPERATIONS},
            "error_recovery": {"raw": error_recovery_count, "normalized": round(norm_recovery, 3), "weight": WEIGHT_ERROR_RECOVERY},
            "similarity": {"raw": round(pattern_similarity, 3), "normalized": round(norm_similarity, 3), "weight": WEIGHT_SIMILARITY},
        },
    }


# ── Pattern Detection ────────────────────────────────────────

def analyze_daily_logs(workspace: str) -> list:
    """Analyze daily memory logs for repeated patterns."""
    memory_dir = Path(workspace) / MEMORY_DIR
    if not memory_dir.exists():
        return []

    patterns = []
    for log_file in sorted(memory_dir.glob("????-??-??.md")):
        content = log_file.read_text(encoding="utf-8")
        # Look for repeated action verbs
        action_patterns = re.findall(
            r"(?:使用|用|运行|执行|调用|创建|生成|分析|查询|搜索|修改|更新|添加|安装|配置|初始化|重建|推送|同步)\s+(\S+)",
            content
        )
        if action_patterns:
            patterns.append({
                "date": log_file.stem,
                "actions": action_patterns,
                "content_length": len(content),
            })

    return patterns


def detect_tool_patterns(workspace: str) -> list:
    """Detect repeated tool sequences from FTS5 index."""
    db_path = Path(workspace) / ".workbuddy" / "session_index.db"
    if not db_path.exists():
        return []

    patterns = []
    try:
        conn = sqlite3.connect(str(db_path))
        rows = conn.execute(
            "SELECT date, topic, content FROM session_fts"
        ).fetchall()

        for date, topic, content in rows:
            # Extract tool-like patterns
            tool_mentions = re.findall(
                r"(?:python3|bash|Read|Write|Edit|WebFetch|WebSearch|Skill)"
                r"[\s\S]*?(?:\n|$)",
                content
            )
            if len(tool_mentions) >= MIN_COMPLEXITY_SCORE:
                patterns.append({
                    "date": date,
                    "topic": topic,
                    "tool_count": len(tool_mentions),
                    "complexity": "high" if len(tool_mentions) >= 5 else "medium",
                })
        conn.close()
    except Exception:
        pass

    return patterns


def calculate_skill_candidates(workspace: str, use_composite: bool = True) -> list:
    """
    计算 Skill 候选列表。

    Args:
        workspace: 工作区路径
        use_composite: True=使用 Phase 3 复合评分, False=使用旧版简单阈值

    Returns:
        candidates 列表，复合模式下每个 candidate 包含 composite_score 字段
    """
    candidates = []

    # Analyze daily logs
    log_patterns = analyze_daily_logs(workspace)
    action_counts = {}
    for entry in log_patterns:
        for action in entry["actions"]:
            action_counts[action] = action_counts.get(action, 0) + 1

    # Repeated actions are candidates
    for action, count in action_counts.items():
        if count >= MIN_SESSION_OCCURRENCES:
            candidates.append({
                "type": "repeated_action",
                "action": action,
                "occurrences": count,
                "priority": "medium" if count >= 3 else "low",
                "suggestion": f"你经常执行「{action}」相关操作，可以创建一个 Skill 来自动化"
            })

    # Analyze FTS5 for complex sessions
    tool_patterns = detect_tool_patterns(workspace)
    for pattern in tool_patterns:
        if pattern["complexity"] == "high":
            candidates.append({
                "type": "complex_session",
                "topic": pattern["topic"],
                "date": pattern["date"],
                "tool_count": pattern["tool_count"],
                "priority": "high",
                "suggestion": f"「{pattern['topic']}」使用了 {pattern['tool_count']} 次工具调用，"
                              f"适合固化为 Skill"
            })

    # ── Phase 3: 复合评分增强 ──
    if use_composite and log_patterns:
        # 汇总所有日志内容用于分析
        memory_dir = Path(workspace) / MEMORY_DIR
        all_content = ""
        total_tool_calls = 0
        total_file_ops = 0
        total_error_recovery = 0

        for log_file in sorted(memory_dir.glob("????-??-??.md")):
            try:
                content = log_file.read_text(encoding="utf-8")
                all_content += content + "\n"
                total_file_ops += count_file_operations(content)
                total_error_recovery += detect_error_recovery(content)
                # 粗略统计工具调用：Read/Write/Edit/Bash/WebFetch/WebSearch/Skill
                total_tool_calls += len(re.findall(
                    r'\b(?:Read|Write|Edit|Bash|WebFetch|WebSearch|Skill|Glob|Grep|Agent|TaskCreate|TaskUpdate)\b',
                    content
                ))
            except Exception:
                continue

        # 计算跨会话相似度
        similarity = compute_pattern_similarity(log_patterns)

        # 计算复合评分
        composite = calculate_composite_score(
            tool_call_count=total_tool_calls,
            file_op_count=total_file_ops,
            error_recovery_count=total_error_recovery,
            pattern_similarity=similarity,
        )

        # 如果复合评分达标，添加 high-priority 候选
        if composite["meets_threshold"]:
            dims = composite["dimensions"]
            candidates.insert(0, {
                "type": "composite_workflow",
                "priority": "high",
                "composite_score": composite["composite_score"],
                "meets_auto_install": composite["meets_auto_install"],
                "dimensions": dims,
                "hard_thresholds": composite["hard_thresholds"],
                "tool_calls": total_tool_calls,
                "file_ops": total_file_ops,
                "error_recovery": total_error_recovery,
                "pattern_similarity": round(similarity, 3),
                "suggestion": (
                    f"复合评分 {composite['composite_score']:.3f} "
                    f"(工具{total_tool_calls}次/文件{total_file_ops}次/恢复{total_error_recovery}次/相似度{similarity:.2f}) — "
                    f"{'建议自动创建 Skill' if composite['meets_auto_install'] else '建议手动审核后创建 Skill'}"
                ),
            })

    return sorted(candidates, key=lambda x: (
        {"high": 0, "medium": 1, "low": 2}.get(x["priority"], 3)
    ))


def generate_skill_template(name: str, description: str = "",
                             steps: list = None,
                             trigger: str = "",
                             composite_score: float = 0.0,
                             threshold: float = COMPOSITE_SCORE_THRESHOLD) -> str:
    """Generate a SKILL.md template."""
    now = datetime.now().strftime("%Y-%m-%d")
    title = name.replace("-", " ").title()

    return SKILL_TEMPLATE.format(
        name=name,
        description=description or f"Auto-generated skill for {title}",
        title=title,
        trigger_conditions=trigger or f"When the user asks about {title.lower()}",
        steps="\n".join(f"{i+1}. {s}" for i, s in enumerate(steps or ["(步骤待填写)"])),
        configuration="无特殊配置",
        date=now,
        composite_score=composite_score,
        threshold=threshold,
    )


# ── CLI ───────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Skill Auto-Creation Detector for WorkBuddy (Hermes-inspired)"
    )
    parser.add_argument("--workspace", "-w", required=False,
                        help="WorkBuddy workspace path")
    parser.add_argument("--check", action="store_true",
                        help="Quick check for skill creation candidates")
    parser.add_argument("--analyze", action="store_true",
                        help="Detailed pattern analysis (now uses sequence_analyzer)")
    parser.add_argument("--list-patterns", action="store_true",
                        help="List all detected patterns")
    parser.add_argument("--generate", action="store_true",
                        help="Generate a skill template")
    parser.add_argument("--name", type=str,
                        help="Skill name (for --generate)")
    parser.add_argument("--description", type=str, default="",
                        help="Skill description (for --generate)")
    parser.add_argument("--steps", type=str, default="",
                        help="Skill steps, comma-separated (for --generate)")
    parser.add_argument("--auto-install", action="store_true",
                        help="Auto-install skill when confidence >= 0.7 (Phase 3E)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Dry-run mode: detect but don't install (Phase 3E)")
    parser.add_argument("--all-workspaces", action="store_true",
                        help="Analyze all workspaces (Phase 3E)")
    parser.add_argument("--json", action="store_true",
                        help="Output as JSON")

    args = parser.parse_args()

    # Generate skill template
    if args.generate:
        if not args.name:
            print("ERROR: --name is required with --generate", file=sys.stderr)
            sys.exit(1)

        steps = [s.strip() for s in args.steps.split(",") if s.strip()] if args.steps else []
        template = generate_skill_template(
            name=args.name,
            description=args.description,
            steps=steps if steps else None,
        )
        skill_dir = SKILLS_DIR / args.name
        skill_dir.mkdir(parents=True, exist_ok=True)
        skill_path = skill_dir / "SKILL.md"
        skill_path.write_text(template, encoding="utf-8")

        if args.json:
            print(json.dumps({
                "generated": True,
                "path": str(skill_path),
                "name": args.name,
            }, ensure_ascii=False, indent=2))
        else:
            print(f"✅ Skill generated: {skill_path}")
            if steps:
                print(f"   Steps: {len(steps)} defined")
        return

    # All-workspaces analysis (Phase 3E)
    if args.all_workspaces:
        import subprocess
        seq_script = SCRIPTS_DIR / "sequence_analyzer.py"
        workspaces = []
        workbuddy_root = WORKBUDDY_ROOT
        if workbuddy_root.exists():
            for d in workbuddy_root.iterdir():
                if (d / ".workbuddy" / "memory").exists():
                    workspaces.append(str(d))

        all_candidates = []
        for ws in workspaces:
            candidates = calculate_skill_candidates(ws)
            for c in candidates:
                c["workspace"] = Path(ws).name
            all_candidates.extend(candidates)

        if args.json:
            print(json.dumps({
                "workspaces_analyzed": len(workspaces),
                "total_candidates": len(all_candidates),
                "candidates": all_candidates,
            }, ensure_ascii=False, indent=2))
        else:
            print(f"📊 Analyzed {len(workspaces)} workspace(s)")
            print(f"   Found {len(all_candidates)} candidate(s)\n")
            high = [c for c in all_candidates if c["priority"] == "high"]
            if high:
                print(f"   🔴 {len(high)} high-priority candidates:")
                for c in high[:5]:
                    print(f"      [{c.get('workspace', '?')}] {c['suggestion'][:80]}")
        return

    if not args.workspace:
        print("ERROR: --workspace is required unless using --all-workspaces or --generate",
              file=sys.stderr)
        sys.exit(1)

    # Check / analyze
    candidates = calculate_skill_candidates(args.workspace)

    if args.check:
        if args.json:
            # 提取复合评分候选信息
            composite_candidates = [c for c in candidates if c.get("type") == "composite_workflow"]
            output = {
                "candidates": len(candidates),
                "high_priority": len([c for c in candidates if c["priority"] == "high"]),
            }
            if composite_candidates:
                c = composite_candidates[0]
                output["composite_score"] = c.get("composite_score", 0)
                output["meets_auto_install"] = c.get("meets_auto_install", False)
                output["hard_thresholds"] = c.get("hard_thresholds", {})
                output["dimensions"] = c.get("dimensions", {})
            print(json.dumps(output, ensure_ascii=False, indent=2))
        else:
            if not candidates:
                print("✅ No skill creation candidates detected.")
            else:
                high = len([c for c in candidates if c["priority"] == "high"])
                print(f"🔍 Found {len(candidates)} candidate(s), {high} high priority")
                for c in candidates[:5]:
                    icon = "🔴" if c["priority"] == "high" else "🟡"
                    prefix = ""
                    if c.get("type") == "composite_workflow":
                        prefix = f" [复合 {c.get('composite_score', 0):.3f}]"
                    print(f"   {icon}{prefix} {c['suggestion'][:100]}")
        return

    if args.analyze or args.list_patterns:
        # Enhanced analyze with sequence analyzer (Phase 3E)
        if args.dry_run or args.auto_install:
            import subprocess as sp
            seq_path = SCRIPTS_DIR / "sequence_analyzer.py"
            score_path = SCRIPTS_DIR / "confidence_scorer.py"

            if seq_path.exists() and score_path.exists():
                try:
                    result = sp.run(
                        [sys.executable, str(seq_path), "--workspace", args.workspace,
                         "--cluster", "--json"],
                        capture_output=True, text=True, timeout=30,
                    )
                    if result.returncode == 0:
                        seq_data = json.loads(result.stdout)
                        patterns = seq_data.get("patterns", [])

                        if patterns:
                            # Score patterns
                            score_input = json.dumps(patterns)
                            score_result = sp.run(
                                [sys.executable, str(score_path), "--score", score_input, "--json"],
                                capture_output=True, text=True, timeout=15,
                            )
                            if score_result.returncode == 0:
                                scored = json.loads(score_result.stdout)
                                if args.auto_install:
                                    auto_candidates = [s for s in scored
                                                      if s.get("meets_auto_install", False)]
                                else:
                                    auto_candidates = [s for s in scored
                                                      if s.get("meets_dry_run", False)]

                                if args.json:
                                    print(json.dumps({
                                        "mode": "auto-install" if args.auto_install else "dry-run",
                                        "patterns_found": len(patterns),
                                        "candidates": len(auto_candidates),
                                        "details": auto_candidates,
                                    }, ensure_ascii=False, indent=2))
                                else:
                                    mode = "AUTO-INSTALL" if args.auto_install else "Dry-run"
                                    print(f"🔬 {mode} analysis:")
                                    print(f"   Patterns found: {len(patterns)}")
                                    print(f"   Candidates: {len(auto_candidates)}")
                                    if auto_candidates:
                                        print()
                                        for i, s in enumerate(auto_candidates, 1):
                                            rep = s["pattern"].get("representative_sequence", "?")[:80]
                                            score = s["composite_score"]
                                            print(f"   [{i}] Score: {score:.3f} — {rep}")
                                            if args.auto_install:
                                                # Auto-install the skill
                                                skill_name = f"auto-skill-{i}"
                                                template = generate_skill_template(
                                                    name=skill_name,
                                                    description=f"Auto-generated from workflow: {rep}",
                                                    steps=[rep],
                                                    trigger=f"Automatic workflow: {rep}",
                                                )
                                                skill_dir = SKILLS_DIR / skill_name
                                                skill_dir.mkdir(parents=True, exist_ok=True)
                                                (skill_dir / "SKILL.md").write_text(
                                                    template, encoding="utf-8")
                                                print(f"      ⚡ Auto-installed: {skill_dir / 'SKILL.md'}")
                                    return
                except Exception:
                    pass  # Fall through to regular analyze

        # Fallback to regular analyze
        if args.json:
            print(json.dumps(candidates, ensure_ascii=False, indent=2))
        else:
            if not candidates:
                print("🔍 No reusable patterns detected yet.")
                print("   Patterns emerge after multiple sessions with similar workflows.")
            else:
                print(f"🔍 Detected {len(candidates)} pattern(s):\n")
                for i, c in enumerate(candidates, 1):
                    icon = "🔴" if c["priority"] == "high" else "🟡" if c["priority"] == "medium" else "⚪"
                    print(f"  {icon} [{i}] {c['type']}: {c.get('action', c.get('topic', ''))}")
                    print(f"      {c['suggestion'][:100]}")
                    print()
        return

    # Default: quick check
    if candidates:
        print(f"🔍 {len(candidates)} skill candidate(s) found. Use --analyze for details.")
    else:
        print("✅ No skill candidates yet.")


if __name__ == "__main__":
    main()
